import type { Metadata } from 'next'
import { Geist, Geist_Mono, Figtree } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import { TooltipProvider } from '@/components/ui/tooltip'
import { SessionProvider } from 'next-auth/react'
import { auth } from '@/auth'
import { OverlayProvider } from '@/hooks/contexts/use-overlay'
import { Toaster } from '@/components/ui/sonner'
import { ProjectProvider } from '@/hooks/contexts/project-provider'
import { categoryRepository, projectRepository } from '@/core/repositories'

const figtree = Figtree({ subsets: ['latin'], variable: '--font-sans' })

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'MINI GALLERY',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()
  const projects = await projectRepository.findAllWithCategory()
  const categories = await categoryRepository.findAll()
  return (
    <html
      lang="en"
      className={cn(
        'h-full',
        'antialiased',
        geistSans.variable,
        geistMono.variable,
        'font-sans',
        figtree.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <ProjectProvider initProjects={projects} initCategories={categories}>
          <SessionProvider session={session} refetchOnWindowFocus={false}>
            <OverlayProvider>
              <TooltipProvider>{children}</TooltipProvider>
            </OverlayProvider>
            <Toaster position="top-right" />
          </SessionProvider>
        </ProjectProvider>
      </body>
    </html>
  )
}
